# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ssh_username = 'ec2-user'
  region = 'ap-northeast-1' # FIXME
  ami = 'ami-6c3c130b' # FIXME
  instance_type = 't2.micro'
  keyname = 'default-key' # FIXME

  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.aws_dir = ENV['HOME'] + "/.aws/"
    aws.aws_profile = "default"
    aws.keypair_name              = keyname
    override.ssh.username         = ssh_username
    override.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa_ec2" # FIXME
    # aws.private_ip_address = ''

    aws.region = region
    aws.elastic_ip = false
    aws.subnet_id = 'subnet-c085c398'  # FIXME
    aws.security_groups = %w[sg-ed94588b sg-ed94588b] # FIXME

    aws.tags = { 'Name' => 'HelloVagrant' } # FIXME
    aws.ami = ami
    aws.instance_type = instance_type

    # config.ssh.proxy_command = '' # FIXME
    # config.ssh.forward_agent
    # config.ssh.forward_env
    # config.ssh.keep_alive
  end
end
