# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

yaml_config = YAML.load_file 'config.yml'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ssh_username = 'ec2-user'

  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.aws_dir = ENV['HOME'] + "/.aws/"
    aws.aws_profile = yaml_config['profile']
    aws.keypair_name              = yaml_config['keyname']
    override.ssh.username         = ssh_username
    override.ssh.private_key_path = yaml_config['private_key_path']
    # aws.private_ip_address = ''

    aws.region = yaml_config['region']
    aws.elastic_ip = false
    aws.subnet_id = yaml_config['subnet_ids']
    aws.security_groups = yaml_config['security_groups']

    aws.tags = yaml_config['tags']
    aws.ami = yaml_config['ami']
    aws.instance_type = yaml_config['instance_type']

    # config.ssh.proxy_command = '' # FIXME
    # config.ssh.forward_agent
    # config.ssh.forward_env
    # config.ssh.keep_alive
  end
end
