# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

if File.exist?("#{ENV['HOME']}/.aws/credentials")
  require 'inifile'

  inifile = IniFile.load("#{ENV['HOME']}/.aws/credentials")
  access_key = inifile['default']['aws_access_key_id']
  secret_access_key = inifile['default']['aws_secret_access_key']
else
  access_key = ENV['AWS_ACCESS_KEY_ID']
  secret_access_key = ENV['AWS_SECRET_KEY']
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ssh_username = 'ec2-user'
  region = 'ap-northeast-1'
  ami = 'ami-859bbfe2'
  instance_type = 't2.micro'
  keyname = 'vagrant'

  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.access_key_id             = access_key
    aws.secret_access_key         = secret_access_key
    aws.keypair_name              = keyname
    override.ssh.username         = ssh_username
    override.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa"

    aws.region = region
    aws.elastic_ip = true
    aws.security_groups = %w[default ssh]

    aws.tags = { 'Name' => 'HelloVagrant' }
    aws.ami = ami
    aws.instance_type = instance_type
  end
end
