from os import getenv

DEBUG = getenv('FLASK_DEBUG') or False

SWAGGER_UI_DOC_EXPANSION = 'list'

RESTPLUS_VALIDATE = True

PORT = getenv('FLASKR_PORT') or 5000

SQLALCHEMY_DATABASE_URI = getenv('FLASKR_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = True
