#!/bin/sh

USAGE=$(cat <<...
Usage:
  log-start [-h]: start logging

Options:
    -h: show this usage.

Descriptions:
  This script is script simple wrapper.
  To decode log file, do this command.

     col -bx < log-file

  For more information, see \`script -h\`
...
)

if [ "$1" = '-h' ] ; then
    echo "${USAGE}"
    script -h
    exit 0
fi

if [ ! -e "$HOME/.log" ] ; then
    mkdir -p "$HOME/.log"
fi
script "$@" "$HOME/.log/script-$(date +%Y%m%d-%H%M%S).log"
