#!/bin/sh

## variables
work_dir='/tmp'
mount_point_ipxe="${work_dir}/ipxe"
mount_point_dest="${work_dir}/dest"
ipxe_iso_url='http://boot.ipxe.org/ipxe.iso'
ipxe_iso='ipxe.iso'
dest_img="$(pwd)/pxeboot.img"

## make working directory
pushd "${work_dir}"
sudo rm -rf "${mount_point_dest}" "${mount_point_ipxe}"
mkdir "${mount_point_dest}" "${mount_point_ipxe}"

## make, mount and format image
dd if=/dev/zero of="${dest_img}" bs=1M count=4
mkdosfs "${dest_img}"
sudo mount -o loop "${dest_img}" "${mount_point_dest}"
loopback_device=$(losetup -j "${dest_img}" | awk -F ':' '{print $1}')
sudo syslinux --install "${loopback_device}"

## get ipxe kernel
wget "${ipxe_iso_url}"
sudo mount -o loop "${ipxe_iso}" "${mount_point_ipxe}"

## make neccessary files for syslinux
sudo cp "${mount_point_ipxe}"/ipxe.krn "${mount_point_dest}"
cat <<'...' | sudo tee "${mount_point_dest}"/syslinux.cfg >/dev/null
DEFAULT ipxe
LABEL ipxe
    KERNEL ipxe.krn
...

## swipe working files and directory
sudo umount "${mount_point_ipxe}"
sudo umount "${mount_point_dest}"
losetup -a | awk -F ':' '{print $1}' |xargs -I@@ sudo losetup -d @@
rm -rf  "${mount_point_dest}" "${mount_point_ipxe}" "${ipxe_iso}"

## finish
echo "output: ${dest_img}"
exit 0
