#cloud-config

---
hostname: coreos01
manage_etc_hosts: localhost
coreos:
  update:
    reboot-strategy: best-effort
  units:
  - name: docker.socket
    content: |
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      ListenStream=2375
      Service=docker.service
      BindIPv6Only=both

      [Install]
      WantedBy=sockets.target
  - name: flanneld.service
    drop-ins:
    - name: network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
  - name: timezone.service
    content: |
      [Unit]
      Description=timezone

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/ln -sf ../usr/share/zoneinfo/Japan /etc/localtime
    command: start
    enable: true
write_files: []
users:
- name: core
  passwd: "$1$jP5rZhTg$TnvYZZM4q4hyyBQ93tCiu1"
  groups:
  - sudo
  - docker
