# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ssh_username = 'ec2-user'
  region = 'ap-northeast-1'
  ami = 'ami-b1fe9bb0'
  instance_type = 't1.micro'

  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.access_key_id             = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key         = ENV['AWS_SECRET_KEY']
    aws.keypair_name              = ENV['AWS_KEYPAIR_NAME']
    override.ssh.username         = ssh_username
    override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']

    aws.region = region
    aws.elastic_ip = true
    aws.security_groups = ['default']

    # aws.tags = {"Name" => ""}
    aws.ami = ami
    aws.instance_type = instance_type
  end
end
