# -*- mode: ruby -*-
# vi: set ft=ruby :

Dotenv.load

VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end

  config.vm.box = 'opscode_centos-7.1'
  config.vm.hostname = ENV['vb_hostname'] || 'centos71'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box'
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = ENV['vb_gui'] || false
    vb.cpus = ENV['vb_cpus'] || 1
    vb.memory = ENV['vb_memory'] || 1024
  end

  config.ssh.forward_agent = true
  config.vm.network :private_network, type: 'dhcp'

  if Vagrant.has_plugin?('vagrant-hostupdater')
    config.hostsupdater.aliases = [hostname]
    config.hostsupdater.remove_on_suspend = true
  end

  config.vm.synced_folder './export', '/export', \
                          mount_options: ['dmode=775', 'fmode=644']

  config.omnibus.chef_version  =  :latest
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['./cookbooks', './site-cookbooks']
    chef.environments_path = './environments'
    chef.roles_path = './roles'
    chef.run_list = %w(
      recipe[yum]
      recipe[yum-epel]
      recipe[git]
      recipe[zsh]
      recipe[deploy]
      recipe[develop::golang]
    )
  end
end
