# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
$vb_gui = false
$vb_memory = 1024
$vb_cpus = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hostname = "centos70"
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end
  config.vm.box = "opscode_centos-7.0"
  config.vm.hostname = hostname
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
 config.vm.provider "virtualbox" do |vb|
   vb.gui = $vb_gui
   vb.cpus = $vb_cpus
   vb.memory = $vb_memory
 end
  config.vm.network :private_network, ip: "192.168.33.10"
  if Vagrant.has_plugin?("vagrant-hostupdater")
    config.hostsupdater.aliases = [hostname]
    config.hostsupdater.remove_on_suspend = true
  end

  config.vm.network :forwarded_port, host: 8000, guest: 8000

  config.vm.synced_folder "./export", "/export"

  config.omnibus.chef_version  =  :latest
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [ "./cookbooks", "./site-cookbooks" , "./berks-cookbooks"]
    chef.environments_path = "./environments"
    chef.roles_path = "./roles"
    chef.json = {
        vim: {
            install_method: "source"
        }
    }
    chef.run_list = %w[
      recipe[yum]
      recipe[yum-epel]
      recipe[git]
      recipe[zsh]
      recipe[deploy]
      recipe[develop::golang]
    ]
  end
end
