# vim: ft=ruby

require 'yaml'
require 'vagrant-openstack-plugin'

params = YAML.load_file('./config.yml')

Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box'
  config.ssh.private_key_path = params[:server][:ssh][:key_path]
  config.ssh.pty = true

  config.vm.provider :openstack do |os|
    os.username = params[:identity][:username]
    os.api_key = params[:identity][:password]
    os.endpoint = params[:identity][:endpoint]

    os.server_name = params[:server][:server_name]
    os.flavor = params[:server][:flavor]
    os.image = params[:server][:image]
    os.keypair_name = params[:server][:keypair]

    os.ssh_username = params[:server][:ssh][:username]
    os.ssh_password = params[:server][:ssh][:password]
    os.ssh_ip_family = params[:server][:ssh][:ip_family]

    os.metadata = params[:server][:metadata]
    os.user_data = params[:server][:user_data]
    os.networks = params[:server][:networks]
		os.scheduler_hints = params[:server][:scheduler_hints]
    os.availability_zone = params[:server][:availability_zone]
    os.security_groups = params[:server][:security_groups]
    os.floating_ip = :auto
    # os.floating_ip_pool = floating_ip_pool
    #
  end
end
