site :opscode

cookbook 'yum'
cookbook 'yum-epel'
cookbook 'vim', git: 'https://github.com/opscode-cookbooks/vim.git'
cookbook 'git'
cookbook 'zsh'
cookbook 'deploy', path: '../../cookbooks/deploy'
cookbook 'develop', path: '../../cookbooks/develop'
