# -*- mode: ruby -*-
# vi: set ft=ruby shiftwidth=2:

VAGRANTFILE_API_VERSION = '2'.freeze

conf_file = File.join(File.dirname(__FILE__), 'config.rb')
userfile = File.join(File.dirname(__FILE__), 'userdata')
userdata = File.read(userfile) if File.exist?(userfile)

$hostname = 'centos7'
$os = 'centos/7'
$vb_gui = false
$vb_memory = 1024
$vb_cpus = 1
$shared_folders = {}
$forwarded_ports = {}
$check_update = false

require conf_file if File.exist?(conf_file)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = $hostname
  config.vm.box = $os
  config.vm.box_check_update = $check_update

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = $vb_gui
    vb.cpus = $vb_cpus
    vb.memory = $vb_memory
  end

  config.ssh.forward_agent = true
  if $vb_fixed_ip
    config.vm.network :private_network, ip: vb_fixed_ip
  else
    config.vm.network :private_network, type: 'dhcp'
  end

  $shared_folders.each do |(host_folder, guest_folder)|
    config.vm.synced_folder host_folder.to_s,
                            guest_folder.to_s,
                            mount_options: ['dmode=775', 'fmode=644']
  end

  $forwarded_ports.each do |host, guest|
    config.vm.network 'forwarded_port',
                      guest: guest, host: host,
                      auto_correct: true
  end

  config.vm.provision :shell, inline: userdata
end
