# vi: set ft=ruby:
require 'yaml'

VAGRANTFILE_API_VERSION = '2'.freeze

userfile = File.join(File.dirname(__FILE__), 'userdata')
userdata = File.read(userfile) if File.exist?(userfile)

params = YAML.load_file('./config.yml')

def vhost_dos?
  RUBY_PLATFORM.downcase =~ /mswin(?!ce)|mingw|cygwin|bccwin/
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = params[:hostname]
  config.vm.box = params[:box]
  config.vm.box_check_update = params[:check_update]

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = params[:gui]
    vb.cpus = params[:cpus]
    vb.memory = params[:memory]
  end

  config.ssh.forward_agent = true
  if params[:fixed_ip]
    config.vm.network :private_network, ip: params[:fixed_ip]
  else
    config.vm.network :private_network, type: 'dhcp'
  end

  config.vm.synced_folder '.', '/vagrant', type: nil if vhost_dos?
  if params[:forwarded_ports]
    params[:forwarded_ports].each do |host, guest|
      config.vm.network 'forwarded_port',
                        guest: guest, host: host,
                        auto_correct: true
    end
  end

  if vhost_dos?
    config.vm.provision :shell, privileged: false, inline: userdata
  else
    config.vm.provision :ansible do |ansible|
      ansible.playbook = 'site.yml'
    end
  end
end
