#!/bin/sh -e
USAGE=$(cat <<...
Usage:
  ansible-check [options] Run \`ansible-playbook --list-tasks --list-hosts --list-tags\`

Options:
  see \`ansible-playbook -h\`
...
)

if [ "$1" = '-h' ] ; then
    echo "${USAGE}"
    exit 0
fi

ansible-playbook \
    --list-tasks \
    --list-hosts \
    --list-tags \
    "$@"
